version: '3.8'
services:
  phind_ai:
    build:
      context: .
      args:
        - NODE_ENV=development
    command: npm run dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: coogle_admin
      POSTGRES_PASSWORD: coogle_2024
      POSTGRES_DB: coogle_ai