version: '3.8'
services:
  meta_ai:
    build:
      context: .
      args:
        - NODE_ENV=development
    command: npm run dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development